#include "entities.h"
#include <algorithm>
#include <cmath>
namespace{constexpr double G=1900;}
Player::Player(const SpriteSheet*s):sheet_(s){}
void Player::reset(QPointF p,bool full){rect_=QRectF(p.x(),p.y(),46,86);vel_={};left_=right_=up_=down_=onGround_=onLadder_=false;direction_=1;shootCd_=invuln_=anim_=0;if(full){health_=5;ammo_=20;score_=0;keys_.clear();}}
void Player::update(double dt,const QVector<QRectF>&platforms,const QVector<QRectF>&ladders,double ww){onLadder_=intersectsAny(rect_,ladders);int h=(right_?1:0)-(left_?1:0);vel_.setX(h*300);if(h)direction_=h>0?1:-1;if(onLadder_&&(up_||down_)){vel_.setY((down_?1:-1)*220);}else vel_.setY(std::min(double(vel_.y())+G*dt,1000.0));onGround_=moveAndCollide(rect_,vel_,dt,platforms).onGround;if(rect_.left()<0)rect_.moveLeft(0);if(rect_.right()>ww)rect_.moveRight(ww);shootCd_=std::max(0.0,shootCd_-dt);invuln_=std::max(0.0,invuln_-dt);anim_+=dt;}
void Player::setLeft(bool v){left_=v;}void Player::setRight(bool v){right_=v;}void Player::setUp(bool v){up_=v;}void Player::setDown(bool v){down_=v;}void Player::jump(){if(onGround_||onLadder_){vel_.setY(-720);onGround_=false;}}
bool Player::canShoot()const{return shootCd_<=0&&ammo_>0;}Projectile Player::shoot(){Projectile b;b.rect=QRectF(direction_>0?rect_.right():rect_.left()-16,rect_.top()+34,16,7);b.velocity=QVector2D(direction_*680,0);--ammo_;shootCd_=.22;return b;}
void Player::damage(double sx){if(invuln_>0||health_<=0)return;--health_;invuln_=1.0;vel_.setY(-400);vel_.setX(rect_.center().x()<sx?-330:330);}void Player::heal(int n){health_=std::min(5,health_+n);}void Player::addAmmo(int n){ammo_=std::min(99,ammo_+n);}void Player::addScore(int n){score_+=n;}void Player::addKey(const QString&k){keys_.insert(k);}bool Player::hasKey(const QString&k)const{return keys_.contains(k);}QRectF Player::rect()const{return rect_;}QPointF Player::position()const{return rect_.topLeft();}int Player::health()const{return health_;}int Player::ammo()const{return ammo_;}int Player::score()const{return score_;}bool Player::dead()const{return health_<=0;}
void Player::draw(QPainter&p,double cx)const{if(!sheet_||!sheet_->valid())return;if(invuln_>0&&int(invuln_*14)%2==0)return;int row=direction_>0?1:0;int col=(std::abs(vel_.x())>1)?1:0;QRect s=sheet_->frame(row,col);QRectF t(rect_.center().x()-s.width()/2.0-cx,rect_.bottom()-s.height(),s.width(),s.height());p.drawImage(t,sheet_->image(),s);}
Enemy::Enemy(const SpriteSheet*s,QString k,QPointF p,double l,double r):sheet_(s),kind_(k),rect_(p.x(),p.y(),46,k=="boss"?100:68),left_(l),right_(r){if(k=="shooter"){speed_=55;hp_=2;}else if(k=="jumper"){speed_=115;hp_=2;}else if(k=="boss"){speed_=70;hp_=12;rect_.setWidth(70);}direction_=int(p.x())%2?1:-1;}
void Enemy::update(double dt,const QVector<QRectF>&ps,QPointF player,QVector<Projectile>&shots){if(hp_<=0)return;double dx=player.x()-rect_.center().x();if(kind_=="boss"||kind_=="shooter")direction_=dx>0?1:-1;vel_.setX(direction_*speed_);if(kind_=="jumper"&&std::abs(dx)<280&&std::abs(vel_.y())<1)vel_.setY(-620);vel_.setY(std::min(double(vel_.y())+G*dt,900.0));auto z=moveAndCollide(rect_,vel_,dt,ps);if(z.hitWall)direction_*=-1;if(rect_.left()<=left_){rect_.moveLeft(left_);direction_=1;}if(rect_.right()>=right_){rect_.moveRight(right_);direction_=-1;}shootCd_-=dt;if((kind_=="shooter"||kind_=="boss")&&std::abs(dx)<620&&shootCd_<=0){Projectile b;b.hostile=true;b.rect=QRectF(rect_.center().x(),rect_.top()+25,13,7);b.velocity=QVector2D((dx>0?1:-1)*(kind_=="boss"?500:380),kind_=="boss"?-40:0);shots<<b;shootCd_=kind_=="boss"?.65:1.35;}anim_+=dt;if(anim_>.18){anim_-=.18;frame_^=1;}}
void Enemy::damage(int n){hp_-=n;}void Enemy::draw(QPainter&p,double cx)const{if(hp_<=0||!sheet_||!sheet_->valid())return;int row=(kind_=="boss"?10:kind_=="jumper"?6:kind_=="shooter"?4:2);QRect s=sheet_->frame(row%11,(direction_>0?2:0)+frame_);QRectF t(rect_.center().x()-s.width()/2.0-cx,rect_.bottom()-s.height(),s.width(),s.height());p.drawImage(t,sheet_->image(),s);if(kind_=="boss"){p.fillRect(QRectF(rect_.left()-cx,rect_.top()-10,rect_.width(),6),Qt::darkRed);p.fillRect(QRectF(rect_.left()-cx,rect_.top()-10,rect_.width()*std::max(0,hp_)/12.0,6),Qt::red);}}QRectF Enemy::rect()const{return rect_;}bool Enemy::alive()const{return hp_>0;}int Enemy::reward()const{return kind_=="boss"?1000:kind_=="walker"?100:200;}
