#include "gamewidget.h"
#include "support.h"
#include <QKeyEvent>
#include <QPainter>
#include <QSettings>
#include <QtMath>
#include <algorithm>
GameWidget::GameWidget(QWidget*p):QWidget(p),playerSheet_(loadTransparentImage(":/sprites/izotop.bmp"),96,128),enemySheet_(loadTransparentImage(":/sprites/potvory.bmp"),64,96),world_(&playerSheet_,&enemySheet_){setWindowTitle("Izotopepa Complete Edition");setFixedSize(W,H);setFocusPolicy(Qt::StrongFocus);QSettings s("OpenAI","Izotopepa");unlocked_=std::clamp(s.value("unlockedLevel",0).toInt(),0,2);timer_.setInterval(16);connect(&timer_,&QTimer::timeout,this,&GameWidget::loop);elapsed_.start();timer_.start();}
void GameWidget::startLevel(int n){world_.loadLevel(n);camera_.configure(W,world_.width());camera_.reset();mode_=Mode::Playing;left_=right_=up_=down_=false;}
void GameWidget::loop(){double dt=std::min(.05,elapsed_.restart()/1000.0);if(dt>0.0){const double instantFps=1.0/dt;fps_=fps_<=0.0?instantFps:(fps_*.9+instantFps*.1);}if(mode_==Mode::Playing){world_.setInput(left_,right_,up_,down_);world_.update(dt);const double cameraDirection=(right_?1.0:0.0)-(left_?1.0:0.0);camera_.update(world_.player().rect().center().x(),cameraDirection,dt);updateMode();}update();}
void GameWidget::updateMode(){if(world_.gameOver())mode_=Mode::GameOver;else if(world_.completed()){unlocked_=std::max(unlocked_,std::min(2,world_.levelIndex()+1));mode_=Mode::Complete;}}
void GameWidget::paintEvent(QPaintEvent*){QPainter p(this);p.setRenderHint(QPainter::Antialiasing,false);drawBackground(p);if(mode_!=Mode::Menu&&mode_!=Mode::Help&&mode_!=Mode::Settings){drawPlatforms(p);world_.draw(p,camera_.x());drawHud(p);}if(mode_==Mode::Menu)drawMenu(p,"IZOTOPEPA: COMPLETE EDITION",{"New game","Select level","Help","Settings","Quit"});else if(mode_==Mode::Paused)drawMenu(p,"PAUSED",{"Resume","Restart level","Main menu"});else if(mode_==Mode::Help)drawMenu(p,"CONTROLS",{"A/D or arrows: move","Space/W/Up: jump or climb","S/Down: climb down","F/Ctrl: shoot","E: activate switch","P/Esc: pause","Backspace: return"});else if(mode_==Mode::Settings)drawMenu(p,"SETTINGS",{QString("Sound: %1").arg(world_.soundEnabled()?"On":"Off"),"Reset saved progress","Back"});else if(mode_==Mode::GameOver)drawMenu(p,"GAME OVER",{"Restart from checkpoint","Restart level","Main menu"});else if(mode_==Mode::Complete)drawMenu(p,"LEVEL COMPLETE",{world_.levelIndex()<2?"Next level":"Play again","Main menu"});}
void GameWidget::drawBackground(QPainter&p){p.fillRect(rect(),QColor(120,195,235));p.setPen(Qt::NoPen);p.setBrush(QColor(75,145,105));for(int i=-1;i<9;++i){double x=i*520-std::fmod(camera_.x()*.18,520.0);p.drawEllipse(QPointF(x+190,575),235,220);}p.setBrush(QColor(255,255,255,210));for(int i=0;i<8;++i){double x=i*600-std::fmod(camera_.x()*.1,600.0),y=80+(i%3)*70;p.drawEllipse(QPointF(x+35,y),30,25);p.drawEllipse(QPointF(x+70,y-10),38,34);p.drawEllipse(QPointF(x+110,y),30,25);}}
void GameWidget::drawPlatforms(QPainter&p){/* Static geometry is intentionally drawn from the level-independent collision silhouette via world objects; ground strip provides visual continuity. */p.fillRect(QRectF(0,570,W,70),QColor(70,110,50));p.fillRect(QRectF(0,570,W,8),QColor(120,175,75));}
void GameWidget::drawHud(QPainter&p){p.setPen(Qt::NoPen);p.setBrush(QColor(20,20,28,220));p.drawRoundedRect(QRectF(12,12,430,80),8,8);p.fillRect(QRectF(25,28,170,20),QColor(60,60,70));p.fillRect(QRectF(25,28,170.0*std::max(0,world_.player().health())/5.0,20),QColor(210,55,55));p.setPen(Qt::white);p.setFont(QFont("Arial",11,QFont::Bold));p.drawText(QRectF(28,25,180,25),Qt::AlignVCenter,QString("Health %1/5").arg(std::max(0,world_.player().health())));p.drawText(QRectF(25,55,400,25),Qt::AlignVCenter,QString("Ammo %1     Score %2     %3").arg(world_.player().ammo()).arg(world_.player().score()).arg(world_.levelName()));if(!world_.message().isEmpty()){p.setBrush(QColor(0,0,0,170));p.setPen(Qt::NoPen);p.drawRoundedRect(QRectF(330,105,300,42),8,8);p.setPen(Qt::yellow);p.drawText(QRectF(330,105,300,42),Qt::AlignCenter,world_.message());}if(debugOverlay_)drawDebugOverlay(p);}
void GameWidget::drawDebugOverlay(QPainter&p){p.save();p.setPen(Qt::NoPen);p.setBrush(QColor(0,0,0,185));p.drawRoundedRect(QRectF(W-220,12,208,88),6,6);p.setPen(QColor(120,255,140));p.setFont(QFont("Monospace",10));const QRectF r(W-210,20,190,70);p.drawText(r,Qt::AlignLeft|Qt::AlignTop,QString("FPS: %1\nCamera X: %2\nLook ahead: %3\nPlayer: %4, %5\nF3: hide debug").arg(fps_,0,'f',1).arg(camera_.x(),0,'f',1).arg(camera_.lookAhead(),0,'f',1).arg(world_.player().rect().x(),0,'f',1).arg(world_.player().rect().y(),0,'f',1));p.restore();}
void GameWidget::drawMenu(QPainter&p,const QString&t,const QStringList&items){p.fillRect(rect(),QColor(0,0,0,150));p.setPen(QColor(255,220,45));p.setFont(QFont("Arial",32,QFont::Bold));p.drawText(QRectF(70,70,W-140,70),Qt::AlignCenter,t);p.setFont(QFont("Arial",17));for(int i=0;i<items.size();++i){QRectF r(180,175+i*55,600,42);if(i==menuIndex_){p.setBrush(QColor(255,220,45,190));p.setPen(Qt::NoPen);p.drawRoundedRect(r,6,6);p.setPen(Qt::black);}else p.setPen(Qt::white);p.drawText(r,Qt::AlignCenter,items[i]);}}
void GameWidget::keyPressEvent(QKeyEvent*e){if(e->isAutoRepeat())return;int k=e->key();if(k==Qt::Key_F3){debugOverlay_=!debugOverlay_;update();return;}if(mode_==Mode::Playing){if(k==Qt::Key_Left||k==Qt::Key_A)left_=true;else if(k==Qt::Key_Right||k==Qt::Key_D)right_=true;else if(k==Qt::Key_Up||k==Qt::Key_W)up_=true;else if(k==Qt::Key_Down||k==Qt::Key_S)down_=true;else if(k==Qt::Key_Space)world_.jump();else if(k==Qt::Key_F||k==Qt::Key_Control)world_.shoot();else if(k==Qt::Key_E)world_.interact();else if(k==Qt::Key_P||k==Qt::Key_Escape){mode_=Mode::Paused;menuIndex_=0;}return;}if(k==Qt::Key_Up){menuIndex_=std::max(0,menuIndex_-1);return;}if(k==Qt::Key_Down){++menuIndex_;return;}if(k==Qt::Key_Backspace||k==Qt::Key_Escape){mode_=Mode::Menu;menuIndex_=0;return;}if(k!=Qt::Key_Return&&k!=Qt::Key_Enter&&k!=Qt::Key_Space)return;
 if(mode_==Mode::Menu){if(menuIndex_==0)startLevel(0);else if(menuIndex_==1){startLevel(unlocked_);}else if(menuIndex_==2){mode_=Mode::Help;menuIndex_=0;}else if(menuIndex_==3){mode_=Mode::Settings;menuIndex_=0;}else close();}
 else if(mode_==Mode::Paused){if(menuIndex_==0)mode_=Mode::Playing;else if(menuIndex_==1)startLevel(world_.levelIndex());else{mode_=Mode::Menu;menuIndex_=0;}}
 else if(mode_==Mode::Settings){if(menuIndex_==0)world_.toggleSound();else if(menuIndex_==1){QSettings("OpenAI","Izotopepa").clear();unlocked_=0;}else{mode_=Mode::Menu;menuIndex_=0;}}
 else if(mode_==Mode::GameOver){if(menuIndex_==0){world_.resetFromCheckpoint();mode_=Mode::Playing;}else if(menuIndex_==1)startLevel(world_.levelIndex());else{mode_=Mode::Menu;menuIndex_=0;}}
 else if(mode_==Mode::Complete){if(menuIndex_==0)startLevel(world_.levelIndex()<2?world_.levelIndex()+1:0);else{mode_=Mode::Menu;menuIndex_=0;}}
}
void GameWidget::keyReleaseEvent(QKeyEvent*e){if(e->isAutoRepeat())return;int k=e->key();if(k==Qt::Key_Left||k==Qt::Key_A)left_=false;else if(k==Qt::Key_Right||k==Qt::Key_D)right_=false;else if(k==Qt::Key_Up||k==Qt::Key_W)up_=false;else if(k==Qt::Key_Down||k==Qt::Key_S)down_=false;else if(k==Qt::Key_Space)world_.stopJump();}
void GameWidget::saveSettings(){}
