#include "world.h"
#include <QApplication>
#include <QPainter>
#include <QRandomGenerator>
#include <QSettings>
#include <QtMath>
#include <algorithm>
World::World(const SpriteSheet*p,const SpriteSheet*e):playerSheet_(p),enemySheet_(e),player_(p){}
bool World::loadLevel(int index){levelIndex_=std::clamp(index,0,2);if(!level_.load(QString(":/levels/level%1.txt").arg(levelIndex_+1)))return false;player_.reset(level_.playerSpawn(),true);respawn_=level_.playerSpawn();enemies_.clear();for(const auto&s:level_.enemies())enemies_<<Enemy(enemySheet_,s.kind,s.position,s.leftLimit,s.rightLimit);moving_.clear();for(const auto&s:level_.moving())moving_<<MovingPlatform{s.rect,s.minX,s.maxX,s.speedX,s.speedY,1,{}};coins_.clear();for(auto p:level_.coins())coins_<<Coin{QRectF(p.x(),p.y(),24,24),false,p.x()*.01};pickups_.clear();for(const auto&s:level_.pickups())pickups_<<Pickup{s.kind,QRectF(s.position.x(),s.position.y(),28,28),false};doors_.clear();for(const auto&s:level_.doors())doors_<<Door{s.key,s.rect,false};switches_.clear();for(const auto&s:level_.switches())switches_<<SwitchObj{s.key,QRectF(s.position.x(),s.position.y(),32,25),false};keys_.clear();for(const auto&s:level_.keys())keys_<<KeyObj{s.key,QRectF(s.position.x(),s.position.y(),26,18),false};projectiles_.clear();particles_.clear();completed_=gameOver_=false;message_=level_.name();messageTime_=2.5;rebuildCollision();return true;}
void World::resetFromCheckpoint(){player_.reset(respawn_,false);gameOver_=false;projectiles_.clear();message_="Checkpoint restart";messageTime_=1.5;}
void World::rebuildCollision(){collision_=level_.platforms();for(const auto&m:moving_)collision_<<m.rect;for(const auto&d:doors_)if(!d.open)collision_<<d.rect;}
void World::update(double dt){if(completed_||gameOver_)return;for(auto&m:moving_){QPointF old=m.rect.topLeft();m.rect.translate(m.speedX*m.dir*dt,m.speedY*m.dir*dt);if((m.speedX!=0&&(m.rect.left()<m.minX||m.rect.left()>m.maxX))||(m.speedY!=0&&(m.rect.top()<250||m.rect.top()>520))){m.dir*=-1;m.rect.moveTopLeft(old);}m.delta=m.rect.topLeft()-old;if(QRectF(player_.rect().translated(0,2)).intersects(m.rect)){} }rebuildCollision();player_.update(dt,collision_,level_.ladders(),level_.worldSize().width());for(auto&e:enemies_)e.update(dt,collision_,player_.rect().center(),projectiles_);
 for(auto&c:coins_){c.phase+=dt*4;if(!c.collected&&player_.rect().intersects(c.rect)){c.collected=true;player_.addScore(10);explode(c.rect.center(),Qt::yellow);beep();}}
 for(auto&p:pickups_)if(!p.taken&&player_.rect().intersects(p.rect)){p.taken=true;if(p.kind=="health")player_.heal(2);else player_.addAmmo(12);message_=p.kind=="health"?"Health restored":"Ammo +12";messageTime_=1.5;beep();}
 for(auto&k:keys_)if(!k.taken&&player_.rect().intersects(k.rect)){k.taken=true;player_.addKey(k.key);message_=k.key+" key acquired";messageTime_=2;beep();}
 for(auto&d:doors_)if(!d.open&&player_.hasKey(d.key)&&player_.rect().adjusted(-8,-8,8,8).intersects(d.rect)){d.open=true;message_=d.key+" door unlocked";messageTime_=2;beep();rebuildCollision();}
 for(const auto&s:level_.spikes())if(player_.rect().intersects(s))player_.damage(s.center().x());
 for(auto&b:projectiles_){if(!b.alive)continue;b.life-=dt;b.rect.translate(b.velocity.x()*dt,b.velocity.y()*dt);if(b.life<=0||intersectsAny(b.rect,collision_)){b.alive=false;explode(b.rect.center(),Qt::lightGray);continue;}if(b.hostile){if(b.rect.intersects(player_.rect())){player_.damage(b.rect.center().x());b.alive=false;explode(b.rect.center(),Qt::red);}}else for(auto&e:enemies_)if(e.alive()&&b.rect.intersects(e.rect())){e.damage(1);b.alive=false;explode(b.rect.center(),Qt::yellow);if(!e.alive()){player_.addScore(e.reward());explode(e.rect().center(),Qt::red);beep();}break;}}
 for(auto&p:particles_){p.life-=dt;p.pos+=p.velocity.toPointF()*dt;p.velocity.setY(p.velocity.y()+400*dt);}projectiles_.erase(std::remove_if(projectiles_.begin(),projectiles_.end(),[](const Projectile&p){return !p.alive;}),projectiles_.end());particles_.erase(std::remove_if(particles_.begin(),particles_.end(),[](const Particle&p){return p.life<=0;}),particles_.end());
 if(level_.checkpoint().x()>=0&&player_.rect().center().x()>level_.checkpoint().x()&&respawn_!=level_.checkpoint()){respawn_=level_.checkpoint();checkpoint();}
 if(player_.rect().intersects(level_.goal())){completed_=true;message_="Level complete!";QSettings s("OpenAI","Izotopepa");s.setValue("unlockedLevel",std::max(s.value("unlockedLevel",0).toInt(),levelIndex_+1));beep();}
 if(player_.dead()||player_.rect().top()>level_.worldSize().height()+100)gameOver_=true;if(messageTime_>0)messageTime_-=dt;else message_.clear();}
void World::setInput(bool l,bool r,bool u,bool d){player_.setLeft(l);player_.setRight(r);player_.setUp(u);player_.setDown(d);}void World::jump(){if(!completed_&&!gameOver_)player_.jump();}void World::shoot(){if(!completed_&&!gameOver_&&player_.canShoot()){projectiles_<<player_.shoot();beep();}}void World::interact(){for(auto&s:switches_)if(!s.active&&player_.rect().adjusted(-25,-10,25,10).intersects(s.rect)){s.active=true;for(auto&d:doors_)if(d.key==s.key)d.open=true;message_="Switch activated";messageTime_=1.5;rebuildCollision();beep();}}
void World::explode(QPointF at,QColor c){for(int i=0;i<10;++i){double a=QRandomGenerator::global()->generateDouble()*6.283;double sp=60+QRandomGenerator::global()->bounded(170);particles_<<Particle{at,QVector2D(qCos(a)*sp,qSin(a)*sp),.35+QRandomGenerator::global()->generateDouble()*.45,3+QRandomGenerator::global()->bounded(5),c};}}
void World::checkpoint(){message_="Checkpoint reached";messageTime_=2;beep();}void World::beep()const{if(sound_)QApplication::beep();}
void World::draw(QPainter&p,double cx)const{for(const auto&platform:level_.platforms()){QRectF r=platform.translated(-cx,0);p.fillRect(r,platform.height()>=60?QColor(70,110,50):QColor(110,78,45));QRectF top=r;top.setHeight(qMin(7.0,r.height()));p.fillRect(top,platform.height()>=60?QColor(120,175,75):QColor(180,135,75));}for(const auto&l:level_.ladders()){QRectF r=l.translated(-cx,0);p.fillRect(r,QColor(135,90,45));p.setPen(QPen(QColor(220,180,100),3));for(double y=r.top()+8;y<r.bottom();y+=18)p.drawLine(QPointF(r.left(),y),QPointF(r.right(),y));}
 for(const auto&m:moving_){QRectF r=m.rect.translated(-cx,0);p.fillRect(r,QColor(95,75,120));p.fillRect(QRectF(r.left(),r.top(),r.width(),5),QColor(185,150,220));}
 for(const auto&s:level_.spikes()){QRectF r=s.translated(-cx,0);QPolygonF poly;double step=20;for(double x=r.left();x<r.right();x+=step)poly<<QPointF(x,r.bottom())<<QPointF(x+step/2,r.top())<<QPointF(x+step,r.bottom());p.setBrush(Qt::darkGray);p.setPen(Qt::NoPen);p.drawPolygon(poly);}
 for(const auto&c:coins_)if(!c.collected){QPointF q(c.rect.center().x()-cx,c.rect.center().y()+qSin(c.phase)*4);p.setBrush(Qt::yellow);p.setPen(QPen(QColor(180,120,0),3));p.drawEllipse(q,11,11);}for(const auto&u:pickups_)if(!u.taken){QRectF r=u.rect.translated(-cx,0);p.setBrush(u.kind=="health"?Qt::red:Qt::cyan);p.setPen(Qt::white);p.drawRoundedRect(r,5,5);p.drawText(r,Qt::AlignCenter,u.kind=="health"?"+":"A");}
 for(const auto&k:keys_)if(!k.taken){QRectF r=k.rect.translated(-cx,0);p.setPen(QPen(Qt::yellow,4));p.drawLine(r.left(),r.center().y(),r.right(),r.center().y());p.drawEllipse(QPointF(r.left()+4,r.center().y()),5,5);}
 for(const auto&d:doors_)if(!d.open){QRectF r=d.rect.translated(-cx,0);p.fillRect(r,QColor(90,55,25));p.setPen(QPen(QColor(220,170,70),3));p.drawRect(r);p.drawEllipse(QPointF(r.right()-12,r.center().y()),3,3);}for(const auto&s:switches_){QRectF r=s.rect.translated(-cx,0);p.fillRect(r,s.active?Qt::green:Qt::darkRed);}
 for(const auto&e:enemies_)e.draw(p,cx);for(const auto&b:projectiles_)p.fillRect(b.rect.translated(-cx,0),b.hostile?Qt::red:Qt::yellow);for(const auto&q:particles_){p.setBrush(q.color);p.setPen(Qt::NoPen);p.drawEllipse(QPointF(q.pos.x()-cx,q.pos.y()),q.size,q.size);}player_.draw(p,cx);}
Player&World::player(){return player_;}const Player&World::player()const{return player_;}double World::width()const{return level_.worldSize().width();}QString World::levelName()const{return level_.name();}int World::levelIndex()const{return levelIndex_;}bool World::completed()const{return completed_;}bool World::gameOver()const{return gameOver_;}void World::toggleSound(){sound_=!sound_;}bool World::soundEnabled()const{return sound_;}QString World::message()const{return message_;}
